version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: compose/app/Containerfile
    restart: always
    environment:
      GOFLAGS: "-buildvcs=false"
      DB_HOST_ADDRESS: db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - .go-build:/root/.cache/go-build

  db:
    image: public.ecr.aws/docker/library/mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "golang_webserver_practise_development"
    ports:
      - 3306:3306
    healthcheck:
      test: 'mysqladmin ping -h 127.0.0.1 -u root'
    volumes:
      - db-data:/var/lib/mysql
      - ./compose/mysql/my.cnf:/etc/my.cnf:ro

volumes:
  db-data:
