version: '3'
services:
  db:
    image: public.ecr.aws/docker/library/mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    healthcheck:
      test: 'mysqladmin ping -h 127.0.0.1 -u root'
    volumes:
      - db-data:/var/lib/mysql
      - ./compose/mysql/my.cnf:/etc/my.cnf:ro

volumes:
  db-data:
