FROM golang:1.20.2

RUN apt update && apt upgrade -y \
    && apt install -y git locales \
    && apt autoremove && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -E 's/# (ja_JP.UTF-8)/\1/' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=ja_JP.UTF-8

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

EXPOSE 3000
CMD ["air", "-c", ".air.toml"]
